### ISSUE TITLE
Consumer should be able to run `npm install` followed by `npm start` without error

### ISSUE THREAD

**Issue by tmrotz** [momadison/igtbok#34]
travis@DESKTOP-4MK1K1Q:/mnt/z/code/igtbok$ npm install
npm WARN lifecycle mern@1.0.0~install: cannot run in wd mern@1.0.0 cd client && npm install (wd=/mnt/z/code/igtbok)
npm WARN enzyme-adapter-react-16@1.14.0 requires a peer of enzyme@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN mern@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 2902 packages in 15.002s
found 0 vulnerabilities

travis@DESKTOP-4MK1K1Q:/mnt/z/code/igtbok$ npm start

> mern@1.0.0 start /mnt/z/code/igtbok
> if-env NODE_ENV=production && npm run start:prod || npm run start:dev

> mern@1.0.0 start:dev /mnt/z/code/igtbok
> concurrently "nodemon --ignore 'client/*'" "npm run client"

[1]
[1] > mern@1.0.0 client /mnt/z/code/igtbok
[1] > cd client && npm run start
[1]
[0] [nodemon] 1.19.1
[0] [nodemon] to restart at any time, enter `rs`
[0] [nodemon] watching: *.*
[0] [nodemon] starting `node server.js`
[0] this is NOT in production
[1]
[1] > mern@0.1.0 start /mnt/z/code/igtbok/client
[1] > react-scripts start
[1]
[1] sh: 1: react-scripts: not found
[1] npm ERR! file sh
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! errno ENOENT
[1] npm ERR! syscall spawn
[1] npm ERR! mern@0.1.0 start: `react-scripts start`
[1] npm ERR! spawn ENOENT
[1] npm ERR!
[1] npm ERR! Failed at the mern@0.1.0 start script.
[1] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[1]
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR!     /home/travis/.npm/_logs/2019-07-25T20_38_51_266Z-debug.log
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! errno 1
[1] npm ERR! mern@1.0.0 client: `cd client && npm run start`
[1] npm ERR! Exit status 1
[1] npm ERR!
[1] npm ERR! Failed at the mern@1.0.0 client script.
[1] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[1]
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR!     /home/travis/.npm/_logs/2019-07-25T20_38_51_311Z-debug.log
[1] npm run client exited with code 1
[0] /mnt/z/code/igtbok/node_modules/passport-oauth2/lib/strategy.js:86
[0]   if (!options.clientID) { throw new TypeError('OAuth2Strategy requires a clientID option'); }
[0]                            ^
[0]
[0] TypeError: OAuth2Strategy requires a clientID option
[0]     at Strategy.OAuth2Strategy (/mnt/z/code/igtbok/node_modules/passport-oauth2/lib/strategy.js:86:34)
[0]     at new Strategy (/mnt/z/code/igtbok/node_modules/passport-google-oauth20/lib/strategy.js:52:18)
[0]     at Object.<anonymous> (/mnt/z/code/igtbok/server.js:27:14)
[0]     at Module._compile (internal/modules/cjs/loader.js:776:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
[0]     at Module.load (internal/modules/cjs/loader.js:643:32)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:556:12)
[0]     at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)
[0]     at internal/main/run_main_module.js:17:11
[0] [nodemon] app crashed - waiting for file changes before starting...

**Comment by tmrotz** [comment]
Update the README if the information is incorrect
